### ISSUE TITLE
NexusScript custom resource

### ISSUE THREAD

**Issue by zmotso** [epam/edp-nexus-operator#17]
NexusScript should contain:
- name
- content(groovy script)
- payload

**Comment by zmotso** [comment]
Done. NexusScript CR example:
```yaml
apiVersion: edp.epam.com/v1alpha1
kind: NexusScript
metadata:
  name: nexusscript-sample
spec:
  name: anonymous
  content: |
    security.setAnonymousAccess(Boolean.valueOf(args))
  payload: "true"
  nexusRef:
    name: nexus-sample
```
