### ISSUE TITLE
NexusRepository validation

### ISSUE THREAD

**Issue by zmotso** [epam/edp-nexus-operator#18]
**Is your feature request related to a problem? Please describe.**

Currently, we can create NexusRepository with multiple formats and types.
Example:

```yaml
apiVersion: edp.epam.com/v1alpha1
kind: NexusRepository
metadata:
  name: npm-hosted
spec:
  nexusRef:
    name: nexus-sample
  npm:
    hosted:
      name: npm-hosted
    proxy:
      name: npm-proxy
      proxy:
        remoteUrl: https://test.com
  go:
    group:
      name: go-group
      group:
          memberNames:
          - go-proxy
```

The operator doesn't support multiple types and formats in one CR. So we will get an error during resource reconciliation.

**Describe the solution you'd like**
Create a validation web-hook to validate NexusRepository.
- Every repository should contain only one format (go,nmp, maven, etc.) and only one type (proxy, group, hosted).
- Don't allow to change format and type.
