### ISSUE TITLE
Add NexusBlobStore custom resource

### ISSUE THREAD

**Issue by zmotso** [epam/edp-nexus-operator#20]
To configure Nexus with EDP, the nexus operator should manage blob stores.
Add NexusBlobStore custom resource for configuring blob stores.

**Comment by zmotso** [comment]
Implemented, NexusBlobStore CR example:
```yaml
apiVersion: edp.epam.com/v1alpha1
kind: NexusBlobStore
metadata:
  name: nexusblobstore-sample
spec:
  name: nexusblobstore-sample
  file:
    path: storage-blobstore/nexusblobstore-sample
  softQuota:
    limit: 1000
    type: spaceUsedQuota
  nexusRef:
    name: nexus-sample
```
