### ISSUE TITLE
Nexus operator can create NexusScript and optionally run it

### ISSUE THREAD

**Issue by zmotso** [epam/edp-nexus-operator#21]
Currently, the Nexus operator creates and runs NexusScript.
Running some scripts is the pipeline's responsibility.
Make the run script step from the NexusScrip reconciliation optional.

**Comment by zmotso** [comment]
Now, by default, NexusScript is not executed automatically after creation.
To execute NexusScript, add **execute: true** property.
Example:
```yaml
apiVersion: edp.epam.com/v1alpha1
kind: NexusScript
metadata:
  name: nexusscript-sample
spec:
  name: anonymous
  content: |
    security.setAnonymousAccess(Boolean.valueOf(args))
  payload: "true"
  execute: true
  nexusRef:
    name: nexus-sample
```
