### ISSUE TITLE
The repository type pypi (hosted) was not created

### ISSUE THREAD

**Issue by zmotso** [epam/edp-nexus-operator#23]
To reproduce create pypi hosted repository
```yaml
apiVersion: edp.epam.com/v1alpha1
kind: NexusRepository
metadata: 
  name: python-hosted
  namespace: nexus
status: 
  error: 'failed to get repository data: no pypi repository set'
  value: error
spec: 
  nexusRef: 
    kind: Nexus
    name: nexus
  pypi: 
    hosted: 
      component: 
        proprietaryComponents: true
      name: edp-python-snapshots
      online: true
      storage: 
        blobStoreName: edp-python
        strictContentTypeValidation: true
        writePolicy: ALLOW_ONCE
```

The repository is not created, and we have the error 'failed to get repository data: no pypi repository set.'
But from the Nexus UI we can create such type of the repository.
