### ISSUE TITLE
Add NexusCleanupPolicy Custom Resource

### ISSUE THREAD

**Issue by zmotso** [epam/edp-nexus-operator#25]
To integrate Nexus with the EDP, we must manage Nexus cleanup policies through custom resources.

**Comment by zmotso** [comment]
Done. CR example:

```yaml
apiVersion: edp.epam.com/v1alpha1
kind: NexusCleanupPolicy
metadata:
  name: nexuscleanuppolicy-sample
spec:
  nexusRef:
    name: nexus-sample
  name: go-cleanup-policy
  format: "go"
  description: "Cleanup policy for go"
  criteria:
    lastBlobUpdated: 30
```
