### ISSUE TITLE
S3 BlobStore can't be defined

### ISSUE THREAD

**Issue by MiKuBB** [epam/edp-nexus-operator#65]
**Describe the bug**
S3 NexusBlobStore can't be created in operator version 3.5.0

**To Reproduce**

#### What did you do?

```
---
apiVersion: edp.epam.com/v1alpha1
kind: NexusBlobStore
metadata:
  name: s3-sample
spec:
  name: s3-sample
  s3:
    bucket:
      name: nexus-test
      region: us-east-1
    bucketSecurity:
      accessKeyId:
        configMapKeyRef:
          name: s3-config
          key: accessKeyId
      secretAccessKey:
        configMapKeyRef:
          name: s3-config
          key: secretAccessKey
    advancedBucketConnection:
      endpoint: https://s3.xxx
  nexusRef:
    name: nexus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-config
data:
  accessKeyId: "xxx"
  secretAccessKey: "xxx"
```

#### What did you expect to see?

nexusblobstore.edp.epam.com/nexusblobstore-sample created

#### What did you see instead? Under which circumstances?

Error from server (BadRequest): error when creating "blobstore-sb01.yaml": NexusBlobStore in version "v1alpha1" cannot be handled as a NexusBlobStore: strict decoding error: unknown field "spec.s3"

**Kubernetes cluster type:**

tanzu

tanzu tkg 1.29.6 

`$ operator-sdk version`

`$ go version`

`$ kubectl version`

Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.29.6+vmware.1
WARNING: version difference between client (1.32) and server (1.29) exceeds the supported minor version skew of +/-1
Kubecolor Version: 0.5.0

**Screenshots**

**Additional context**
