### ISSUE TITLE
Refactor Nexus CR

### ISSUE THREAD

**Issue by zmotso** [epam/edp-nexus-operator#7]
- Remove all configurations from Nexus CR.
- Nexus CR should contain only base parameters to get the connection - URL and credentials.
- Move CR to the group edp and version v1alpha1.
- Update operator dependencies.
- Add integration tests for the Nexus CR.

We can use https://github.com/datadrivers/go-nexus-client to work with Nexus API.

**Comment by zmotso** [comment]
Example of the new Nexus CR.
```yaml
apiVersion: edp.epam.com/v1alpha1
kind: Nexus
metadata:
  name: nexus
spec:
  url: https://nexus-example.com
  secret: nexus-secret
```
