### ISSUE TITLE
Add NexusUser custom resource

### ISSUE THREAD

**Issue by zmotso** [epam/edp-nexus-operator#9]
The user should contain the following fields:
- ID
- First name
- Last name
- Email
- Password
- Status (active, disabled)
- Roles

**Comment by zmotso** [comment]
User CR definition.
```yaml
apiVersion: edp.epam.com/v1alpha1
kind: NexusUser
metadata:
  name: user-sample
spec:
  id: test-user
  firstName: John1
  lastName: Doe
  email: test@gmail.com
  secret: $user-secret:password
  roles:
    - nx-admin
  nexusRef:
    name: nexus-sample
    kind: Nexus
```
